### PR TITLE
Build image from Fedora base

### PR DESCRIPTION
**Pull request by saw-jan**
Since there is an issue with running ubuntu22 based image in drone-ci (see https://github.com/owncloud-ci/squish/issues/34), with this PR, the image can be built on Fedora base which works in drone-ci.

Remaining tasks:
- [x] fix icons not visible
- [x] pipeline for build this image (or remove ubuntu one)
- [x] test in GUI tests pipeline (tests can run: https://drone.owncloud.com/owncloud/client/12948)

### CODE REVIEW

**Comment by saw-jan** [comment]
This is also ready for review. And also have to discuss on whether to keep or remove ubuntu image.

CC @individual-it @TheOneRing @fmoc

**Review by fmoc — COMMENTED** [review]
Seems reasonable to me. The Dockerfile and configs look good.

Please note that Fedora is a short-lived distribution and they tend to break things with every release. I'd recommend you to slowly transition back to Ubuntu LTS later on.

**Comment by saw-jan** [comment]
> Seems reasonable to me. The Dockerfile and configs look good.
> 
> Please note that Fedora is a short-lived distribution and they tend to break things with every release. I'd recommend you to slowly transition back to Ubuntu LTS later on.

So, we need to have both (Ubuntu and Fedora) as for now? And then slowly discard Fedora if using Ubuntu22.04LTS works.

**Comment by saw-jan** [comment]
Possible tags with this PR:
fedora: `fedora`, `fedora-6.7-20220106-1008-qt515x-linux64`, `fedora-36-6.7-20220106-1008-qt515x-linux64`
latest: `latest`, `6.7-20220106-1008-qt515x-linux64`, `u22.04-6.7-20220106-1008-qt515x-linux64`
qt512: `qt512`, `qt512-6.7-20210421-1504-qt512x-linux64`

CC @individual-it @fmoc

**Comment by individual-it** [comment]
let's change the tagging to be more consistent and then I think we can merge this
fedora: `fedora, fedora-6.7-20220106-1008-qt515x-linux64, fedora-36-6.7-20220106-1008-qt515x-linux64`
latest: `latest, ubuntu-6.7-20220106-1008-qt515x-linux64, ubuntu-22.04-6.7-20220106-1008-qt515x-linux64`
qt512: `qt512, qt512-6.7-20210421-1504-qt512x-linux64`

**Comment by fmoc** [comment]
> So, we need to have both (Ubuntu and Fedora) as for now? And then slowly discard Fedora if using Ubuntu22.04LTS works.

What I was trying to say is, let's use Fedora 36 if it works now so that the tests are running again. Then, we have time until Fedora 36 becomes EOL to transition back to, e.g., Ubuntu.

**Review by individual-it — APPROVED** [review]

**Pull request merged**
